# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages


os:
  - linux
 # - osx
dist: trusty

r:
  - release
  - devel
  #- oldrel


env:
   global:
     - R_BUILD_ARGS="--compact-vignettes=gs+qpdf"
     - R_CHECK_ARGS="*tar.gz --as-cran"

addons:
  apt:
    update: true
    packages:
      - libudunits2-dev
      - libgdal-dev
      - qpdf
      - ghostscript

after_success:
  - Rscript -e 'covr::codecov(type = "all")'

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
